package com.myfoundation.school.audit;

public enum AuditAction {
    USER_CREATED,
    USER_DELETED,
    USER_STATUS_CHANGED,
    PASSWORD_CHANGED,
    PASSWORD_SETUP_COMPLETED,
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    ACCOUNT_LOCKED,
    SETTINGS_UPDATED,
    CAMPAIGN_CREATED,
    CAMPAIGN_UPDATED,
    CAMPAIGN_DELETED,
    CATEGORY_CREATED,
    CATEGORY_UPDATED,
    CATEGORY_DELETED
}
